### PR TITLE
Better items.xml and fix little typo [8.60]

### PR DESCRIPTION
**Pull request by Nottinghster**
https: //github.com/hampusborgos/rme/pull/366#issue-957203632
Co-Authored-By: Evil Puncker <4684880+EPuncker@users.noreply.github.com>

### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

**Protocol version**
8.60

### Changes Proposed
1 - Better items.xml
2 - Fix typo (should be dice instead of die)

**Issues addressed:** 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Review by EPuncker — CHANGES_REQUESTED** [review]
good commit, just need to revert magic wall and rush wood changes, and revert `allowpickupable` with `ignoreblocking`, and it can be merged safely

**Comment by EPuncker** [comment]
dustbin still have `allowpickupable` instead of `ignoreblocking`, use replace all function, its safe to change all allowpickupable to ignoreblocking

**Comment by Nottinghster** [comment]
> dustbin still have `allowpickupable` instead of `ignoreblocking`, use replace all function, its safe to change all allowpickupable to ignoreblocking, nekiro just renamed them

All `allowpickupable` are replaced by `ignoreblocking`, check it out 😉

**Comment by Nottinghster** [comment]
@nekiro and @EPuncker this PR is good to go ;)

**Comment by waqmaz93** [comment]
> @nekiro and @EPuncker this PR is good to go ;)

this causes cpu performance problems

**Comment by nekiro** [comment]
Remove that last commit, its not related

**Pull request closed without merging**
