### PR TITLE
Fix pick working on too many tiles

### LINKED ISSUE #51: Pick can be used on too many tiles?
**Protocol version**
7.72

**Describe the bug**
I can use pick on all tiles with ID 354 and 355 (might be more).
Confirmed that it doesn't work on tiles using ID 353, 352 and 351.

**To Reproduce**
1. /i 354
2. Use pick on location
3. Hole appears

**Expected behavior**
Nothing should happen

**Screenshots**
image

### PR DESCRIPTION
**Pull request by dnvd**
resolves #51

### CODE REVIEW

**Comment by dnvd** [comment]
One thing to note here is that I changed the pick hole action id from 105 to 100 since the maps I'm working on uses this for 7.72.
Not sure if this is correct or not. Do you know if TFS used id 100 in the past?

Let me know if you want me to change it back to 105.

**Comment by nekiro** [comment]
Honsetly I don't know xD

**Comment by waqmaz93** [comment]
The real map rom otland has ID 100, so it is fine.

**Comment by EPuncker** [comment]
fixed it properly on: https://github.com/nekiro/TFS-1.5-Downgrades/pull/141

**Pull request closed without merging**
